### PR TITLE
Expand CLI functionality in `main`, make available on earlier Julia versions, and add `.pre-commit-config.yaml`

### LINKED ISSUE #85: Consider adding a pre-commit hook
We are considering how to best use ExplicitImports in Bestie (abelsiqueira/BestieTemplate.jl#349 and abelsiqueira/BestieTemplate.jl#217).
Our current idea is to have a pre-commit hook, like we have for JuliaFormatter and other non-Julia tools.
These hooks also form our Lint workflow, which ensures that even if someone is not using pre-commit, the hooks still run at each PR.
For that to work, we'll need a definition of the pre-commit-hook for ExplicitImports. Although it's possible to create a completely separate repo for that, it's common to have it as part of the main repo (e.g., https://github.com/domluna/JuliaFormatter.jl/blob/master/.pre-commit-hooks.yaml).

Are you open to adding a `.pre-commit-hooks.yml` file here (and possibly an auxiliary script file)?

---

From what I tried so far, it would probably be something like the two files below, although I'm open to suggestions

```yaml
# .pre-commit-hooks.yaml
- id: explicit-imports
  name: "Explicit Imports"
  entry: "pre_commit_explicit_imports.sh"
  args: [Debugging]
  pass_filenames: false
  always_run: false
  types: [file]
  files: \.jl$
  language: "script"
  description: "Checks explicit imports"
```

```sh
#!/bin/bash
# pre_commit_explicit_imports.sh

module=$1

# Check that $module is not empty
if [ -z "$module" ]; then
  echo "Module was not passed. 'args: [Module]' should be passed"
fi

julia -e "
using Pkg
pkg\"activate\"
using ExplicitImports: ExplicitImports
pkg\"activate .\"
using $module
ExplicitImports.check_no_implicit_imports($module)
"
```

### PR DESCRIPTION
**Pull request by abelsiqueira**
Update the CLI at src/main.jl to allow running the checks.
The checks can be defined based on parsed arguments.
Create scripts/explicit-imports.jl to pass ARGS to the CLI when running pre-commit.
Create a pre-commit hook that runs the script.
Move the documentation of CLI from docs/api.md to the README.
Expands the CLI documentation with information on how to run the pre-commit hooks.

Closes #85

---

As I was finishing, I noticed that there is a `src/main.jl` file that is intended to be use as CLI.
The new script is intended to be used as a check tool, so the functionalities are mostly orthogonal.
If you prefer, I can try to merge the two.

As a second note, I haven't seen any place where you run ExplicitImports itself through ExplicitImports.
Let me know if that's on purpose, or if you'd like me to add a check using the script in the CI.
I believe ExplicitImports only pass 2 of the 7 checks, so I would exclude the others.

### CODE REVIEW

**Comment by ericphanson** [comment]
> As I was finishing, I noticed that there is a src/main.jl file that is intended to be use as CLI.
The new script is intended to be used as a check tool, so the functionalities are mostly orthogonal.
If you prefer, I can try to merge the two.

Yeah, we should merge these! `src/main.jl` should be the main CLI driver, the precommit hook should just invoke it.

However currently I am using the `@main` functionality which needs v1.12 (https://docs.julialang.org/en/v1.12-dev/manual/command-line-interface/#The-Main.main-entry-point). I think we can improve backwards compatibility by defining the function as `main(...)` instead of `@main(...)` and then doing
```julia
if @isdefined(var"@main")
    @main
end
```
at the end of the file. My understanding is `@main` just expands to `main`, but also opts-in to the entrypoint functionality, so we don't actually have to define the function as `@main(...)`.

**Comment by ericphanson** [comment]
The other thing is the CLI needs to be expanded to add the `check_*` functions if those are the ones you want to use. Currently the entrypoint just does the `print_` one, which we should keep as the default, but we can use flags to do checks instead.

> As a second note, I haven't seen any place where you run ExplicitImports itself through ExplicitImports.
Let me know if that's on purpose, or if you'd like me to add a check using the script in the CI.
I believe ExplicitImports only pass 2 of the 7 checks, so I would exclude the others.

This is on purpose :). I want to have bits that deliberately fail to have examples for the readme. Also, ExplicitImports is under development (although I've been busy), rather than in a "maintenance" point of its lifecycle, so I don't think at this point its lifecycle it's necessarily worth the tradeoff to use explicit imports everywhere.

**Comment by abelsiqueira** [comment]
Great. I'll start merging the scripts and update the hook. The docs on the `1.12` scripts are only in the `docs/src/api.md` file. Any guidance on how you prefer to merge/update these with my new section in the README?

The tests seem to be broken from something else, by the way. Looks like some change in DataFrames.

**Review by abelsiqueira — COMMENTED** [review]
I've made the corrections and update to merge the CLI. I squashed and rebased the commits, updating the commit and PR description.
I haven't done any extensive testing, just copy-pasted the `-m Module` things for the other direct functionality.
Let me know your thoughts.

**Comment by ericphanson** [comment]
Thanks, this looks great. I took the liberty of pushing up some changes as my form of review, since I wanted to play around with it and try out the CLI changes.

* I renamed `cli` back to `main`, since I think the `-m` functionality is intending to standardize `main` as the CLI entrypoint
* I added `exit(main(...))` as the way to invoke it manually. Otherwise, we call `main` twice on nightly, once manually and once automatically. I also removed all exit invocations from the src code; I really don't want any library usage of ExplicitImports to terminate the whole process, even if you do `ExplicitImports.main(...)`.
* I hid expected stacktraces from `main` calls with try-catches, since they don't point anywhere useful for the user. I decided not to wrap the whole `main` function body in a try-catch, bc that will make debugging hard if there are unexpected crashes.
* I reorganized the README a little bit to put the CLI first and then refer to it for the precommit hooks. I think the CLI is more of a basic primitive and then precommit hooks are one way to use it.

**Review by ericphanson — APPROVED** [review]

**Comment by abelsiqueira** [comment]
Thanks for the changes and thanks for the detailed explanation. I'm really happy with the result.

**Pull request merged**
